(display (null? ())) (newline)
(display (null? 1)) (newline)
(display (pair? (cons 1 2))) (newline)
(display (pair? 42)) (newline)
(display (number? 42)) (newline)
(display (number? "hello")) (newline)
(display (symbol? (quote foo))) (newline)
(display (string? "hello")) (newline)
(display (procedure? car)) (newline)
(display (zero? 0)) (newline)
(display (positive? 5)) (newline)
(display (negative? -3)) (newline)
(display (not #f)) (newline)
(display (not #t)) (newline)
(display (eq? (quote a) (quote a))) (newline)
(display (equal? (list 1 2 3) (list 1 2 3))) (newline)
(display (boolean? #t)) (newline)
(display (boolean? #f)) (newline)
(display (boolean? 42)) (newline)
