# generated by forthc
.text
.global main
main:
    addi r29, r29, -16
    stw r29, r31, 0
    stw r29, r27, 4
    stw r29, r28, 8
    lui r28, %hi(fdstack_top)
    addi r28, r28, %lo(fdstack_top)
    lui r27, %hi(frstack_top)
    addi r27, r27, %lo(frstack_top)
    jal r31, FMAIN
    ldw r31, r29, 0
    ldw r27, r29, 4
    ldw r28, r29, 8
    addi r29, r29, 16
    addi r1, r0, 0
    jalr r0, r31, 0

# . : signed number in current FBASE + trailing space, via debug
FDOT:
    ldw r1, r28, 0
    addi r28, r28, 4
    lui r5, %hi(FBASE)
    addi r5, r5, %lo(FBASE)
    ldw r5, r5, 0
    bge r1, r0, FDOT_pos
    addi r2, r0, 45
    debug r2
    sub r1, r0, r1
FDOT_pos:
    addi r3, r0, 0
FDOT_split:
    rem r4, r1, r5
    div r1, r1, r5
    addi r28, r28, -4
    stw r28, r4, 0
    addi r3, r3, 1
    bne r1, r0, FDOT_split
FDOT_out:
    ldw r4, r28, 0
    addi r28, r28, 4
    addi r6, r0, 10
    blt r4, r6, FDOT_dec
    addi r4, r4, 7
FDOT_dec:
    addi r4, r4, 48
    debug r4
    addi r3, r3, -1
    bne r3, r0, FDOT_out
    addi r4, r0, 32
    debug r4
    jalr r0, r31, 0

# FILL ( addr u ch -- )
FFILL:
    ldw r1, r28, 0
    ldw r2, r28, 4
    ldw r3, r28, 8
    addi r28, r28, 12
    beq r2, r0, FFILL_done
FFILL_loop:
    stb r3, r1, 0
    addi r3, r3, 1
    addi r2, r2, -1
    bne r2, r0, FFILL_loop
FFILL_done:
    jalr r0, r31, 0

# UM/MOD ( ud u -- rem quot ), kernel-verbatim shift-subtract
FUMMOD:
    ldw r3, r28, 0
    ldw r2, r28, 4
    ldw r1, r28, 8
    addi r4, r0, 32
    addi r6, r0, 31
FUMMOD_loop:
    srl r5, r1, r6
    add r1, r1, r1
    add r2, r2, r2
    add r2, r2, r5
    sltu r7, r2, r3
    bne r7, r0, FUMMOD_skip
    sub r2, r2, r3
    addi r1, r1, 1
FUMMOD_skip:
    addi r4, r4, -1
    bne r4, r0, FUMMOD_loop
    addi r28, r28, 4
    stw r28, r1, 0
    stw r28, r2, 4
    jalr r0, r31, 0

# : NIP
FW0:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    addi r28, r28, 4
FL0:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : TUCK
FW1:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
FL1:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ROT
FW2:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
FL2:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : -ROT
FW3:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW2
    jal r31, FW2
FL3:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 2DUP
FW4:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
FL4:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 2DROP
FW5:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, 4
    addi r28, r28, 4
FL5:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 2SWAP
FW6:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW3
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW3
FL6:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 2OVER
FW7:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW6
FL7:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ?DUP
FW8:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL9
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
FL9:
FL8:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : NEGATE
FW9:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
FL10:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : INVERT
FW10:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    xor r2, r2, r1
    stw r28, r2, 0
FL11:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ABS
FW11:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL13
    jal r31, FW9
FL13:
FL12:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : MIN
FW12:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sgt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL15
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
FL15:
    addi r28, r28, 4
FL14:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : MAX
FW13:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    slt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL17
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
FL17:
    addi r28, r28, 4
FL16:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 2*
FW14:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
FL18:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : 0>
FW15:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sgt r2, r2, r1
    stw r28, r2, 0
FL19:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : U>
FW16:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sltu r2, r2, r1
    stw r28, r2, 0
FL20:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : WITHIN
FW17:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sltu r2, r2, r1
    stw r28, r2, 0
FL21:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : TRUE
FW18:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, -1
    stw r28, r1, 0
FL22:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : FALSE
FW19:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
FL23:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CELLS
FW20:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
FL24:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CELL+
FW21:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
FL25:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CHARS
FW22:
    addi r27, r27, -4
    stw r27, r31, 0
FL26:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CHAR+
FW23:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r1, r1, 1
    stw r28, r1, 0
FL27:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ALIGNED
FW24:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 3
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
FL28:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : +!
FW25:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW2
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL29:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D>S
FW26:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, 4
FL30:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : DNEGATE
FW27:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW10
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    jal r31, FW10
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r4, r28, 0
    ldw r3, r28, 4
    ldw r2, r28, 8
    ldw r1, r28, 12
    add r5, r1, r3
    sltu r6, r5, r1
    add r7, r2, r4
    add r7, r7, r6
    addi r28, r28, 8
    stw r28, r7, 0
    stw r28, r5, 4
FL31:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : DABS
FW28:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL33
    jal r31, FW27
FL33:
FL32:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D0=
FW29:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
FL34:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D0<
FW30:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
FL35:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D=
FW31:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r4, r28, 0
    ldw r3, r28, 4
    ldw r2, r28, 8
    ldw r1, r28, 12
    sltu r6, r1, r3
    sub r5, r1, r3
    sub r7, r2, r4
    sub r7, r7, r6
    addi r28, r28, 8
    stw r28, r7, 0
    stw r28, r5, 4
    jal r31, FW29
FL36:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D<
FW32:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW2
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    seq r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL38
    jal r31, FW5
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sltu r2, r2, r1
    stw r28, r2, 0
    jal r0, FL39
FL38:
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sgt r2, r2, r1
    stw r28, r2, 0
    jal r31, FW0
    jal r31, FW0
FL39:
FL37:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : M+
FW33:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    slt r2, r1, r0
    sub r2, r0, r2
    addi r28, r28, -4
    stw r28, r2, 0
    ldw r4, r28, 0
    ldw r3, r28, 4
    ldw r2, r28, 8
    ldw r1, r28, 12
    add r5, r1, r3
    sltu r6, r5, r1
    add r7, r2, r4
    add r7, r7, r6
    addi r28, r28, 8
    stw r28, r7, 0
    stw r28, r5, 4
FL40:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : MU/MOD
FW34:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FUMMOD
    jal r31, FW3
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FUMMOD
    jal r31, FW2
FL41:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SM/REM
FW35:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    xor r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW11
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW28
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FUMMOD
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL43
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    jal r31, FW9
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
FL43:
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL44
    jal r31, FW9
FL44:
FL42:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : FM/MOD
FW36:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW35
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL46
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL47
    ldw r1, r28, 0
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    jal r0, FL45
FL47:
FL46:
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, 4
FL45:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : */MOD
FW37:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    mulh r3, r2, r1
    mul r4, r2, r1
    stw r28, r3, 0
    stw r28, r4, 4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW36
FL48:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : */
FW38:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW37
    jal r31, FW0
FL49:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CMOVE
FW39:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 8
    beq r1, r2, FL53
    addi r27, r27, -8
    stw r27, r1, 0
    stw r27, r2, 4
FL51:
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stb r1, r2, 0
    addi r28, r28, 8
    ldw r1, r27, 0
    ldw r2, r27, 4
    addi r4, r1, 1
    sub r3, r1, r2
    sub r5, r4, r2
    xor r6, r3, r5
    slt r6, r6, r0
    bne r6, r0, FL52
    stw r27, r4, 0
    jal r0, FL51
FL52:
    addi r27, r27, 8
FL53:
    jal r31, FW5
FL50:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : CMOVE>
FW40:
    addi r27, r27, -4
    stw r27, r31, 0
FL55:
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    sne r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL56
    ldw r1, r28, 0
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stb r1, r2, 0
    addi r28, r28, 8
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r0, FL55
FL56:
    addi r28, r28, 4
    jal r31, FW5
FL54:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : /STRING
FW41:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW1
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
FL57:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : COMPARE
FW42:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW2
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW12
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sgt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL59
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 8
    addi r27, r27, -8
    stw r27, r1, 0
    stw r27, r2, 4
FL60:
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    jal r31, FW8
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL63
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL64
    jal r31, FW5
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, 4
    addi r28, r28, -4
    addi r1, r0, -1
    stw r28, r1, 0
    jal r0, FL65
FL64:
    jal r31, FW5
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, 4
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
FL65:
    addi r27, r27, 8
    jal r0, FL58
FL63:
    ldw r1, r27, 0
    ldw r2, r27, 4
    addi r4, r1, 1
    sub r3, r1, r2
    sub r5, r4, r2
    xor r6, r3, r5
    slt r6, r6, r0
    bne r6, r0, FL61
    stw r27, r4, 0
    jal r0, FL60
FL61:
    addi r27, r27, 8
FL62:
    jal r0, FL66
FL59:
    addi r28, r28, 4
FL66:
    jal r31, FW5
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL67
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL68
    addi r28, r28, -4
    addi r1, r0, -1
    stw r28, r1, 0
    jal r0, FL69
FL68:
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
FL69:
FL67:
FL58:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : PLACE
FW43:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    stb r1, r2, 0
    addi r28, r28, 8
    ldw r1, r28, 0
    addi r1, r1, 1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    jal r31, FW39
FL70:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : -TRAILING
FW44:
    addi r27, r27, -4
    stw r27, r31, 0
FL72:
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sgt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL73
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 32
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sne r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL74
    jal r0, FL71
FL74:
    ldw r1, r28, 0
    addi r1, r1, -1
    stw r28, r1, 0
    jal r0, FL72
FL73:
FL71:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SEARCH
FW45:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL76
    jal r31, FW5
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    jal r0, FL75
FL76:
    addi r28, r28, -4
    lui r1, %hi(FD1)
    addi r1, r1, %lo(FD1)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, %hi(FD0)
    addi r1, r1, %lo(FD0)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD1)
    addi r1, r1, %lo(FD1)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    slt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL77
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r0, FL75
FL77:
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD1)
    addi r1, r1, %lo(FD1)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r1, r1, 1
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 8
    beq r1, r2, FL80
    addi r27, r27, -8
    stw r27, r1, 0
    stw r27, r2, 4
FL78:
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD1)
    addi r1, r1, %lo(FD1)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD0)
    addi r1, r1, %lo(FD0)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD1)
    addi r1, r1, %lo(FD1)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW42
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL81
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    addi r27, r27, 8
    jal r0, FL75
FL81:
    ldw r1, r27, 0
    ldw r2, r27, 4
    addi r4, r1, 1
    sub r3, r1, r2
    sub r5, r4, r2
    xor r6, r3, r5
    slt r6, r6, r0
    bne r6, r0, FL79
    stw r27, r4, 0
    jal r0, FL78
FL79:
    addi r27, r27, 8
FL80:
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
FL75:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SPACE
FW46:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 32
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    debug r1
FL82:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SPACES
FW47:
    addi r27, r27, -4
    stw r27, r31, 0
FL84:
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW15
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL85
    jal r31, FW46
    ldw r1, r28, 0
    addi r1, r1, -1
    stw r28, r1, 0
    jal r0, FL84
FL85:
    addi r28, r28, 4
FL83:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : TYPE
FW48:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 8
    beq r1, r2, FL89
    addi r27, r27, -8
    stw r27, r1, 0
    stw r27, r2, 4
FL87:
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    debug r1
    ldw r1, r27, 0
    ldw r2, r27, 4
    addi r4, r1, 1
    sub r3, r1, r2
    sub r5, r4, r2
    xor r6, r3, r5
    slt r6, r6, r0
    bne r6, r0, FL88
    stw r27, r4, 0
    jal r0, FL87
FL88:
    addi r27, r27, 8
FL89:
    addi r28, r28, 4
FL86:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : COUNT
FW49:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r1, r1, 1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
FL90:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ERASE
FW50:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r31, FFILL
FL91:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : BLANK
FW51:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 32
    stw r28, r1, 0
    jal r31, FFILL
FL92:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : <#
FW52:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD2)
    addi r1, r1, %lo(FD2)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 68
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD3)
    addi r1, r1, %lo(FD3)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL93:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : HOLD
FW53:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, -1
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD3)
    addi r1, r1, %lo(FD3)
    stw r28, r1, 0
    jal r31, FW25
    addi r28, r28, -4
    lui r1, %hi(FD3)
    addi r1, r1, %lo(FD3)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stb r1, r2, 0
    addi r28, r28, 8
FL94:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : #>
FW54:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW5
    addi r28, r28, -4
    lui r1, %hi(FD3)
    addi r1, r1, %lo(FD3)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD2)
    addi r1, r1, %lo(FD2)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 68
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD3)
    addi r1, r1, %lo(FD3)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
FL95:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : #
FW55:
    addi r27, r27, -4
    stw r27, r31, 0
    lui r1, %hi(FBASE)
    addi r1, r1, %lo(FBASE)
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW34
    jal r31, FW2
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 10
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    slt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL97
    addi r28, r28, -4
    addi r1, r0, 48
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    jal r0, FL98
FL97:
    addi r28, r28, -4
    addi r1, r0, 10
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 65
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
FL98:
    jal r31, FW53
FL96:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : #S
FW56:
    addi r27, r27, -4
    stw r27, r31, 0
FL100:
    jal r31, FW55
    jal r31, FW4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL100
FL99:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SIGN
FW57:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL102
    addi r28, r28, -4
    addi r1, r0, 45
    stw r28, r1, 0
    jal r31, FW53
FL102:
FL101:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D.
FW58:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW28
    jal r31, FW52
    jal r31, FW56
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW57
    jal r31, FW54
    jal r31, FW48
    jal r31, FW46
FL103:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : U.
FW59:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r31, FW52
    jal r31, FW56
    jal r31, FW54
    jal r31, FW48
    jal r31, FW46
FL104:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : D.R
FW60:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW28
    jal r31, FW52
    jal r31, FW56
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW57
    jal r31, FW54
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    jal r31, FW47
    jal r31, FW48
FL105:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : .R
FW61:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    ldw r1, r28, 0
    slt r2, r1, r0
    sub r2, r0, r2
    addi r28, r28, -4
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW28
    jal r31, FW52
    jal r31, FW56
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW57
    jal r31, FW54
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    jal r31, FW47
    jal r31, FW48
FL106:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : U.R
FW62:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r31, FW52
    jal r31, FW56
    jal r31, FW54
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    jal r31, FW47
    jal r31, FW48
FL107:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : DL,
FW63:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD5)
    addi r1, r1, %lo(FD5)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, 4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    slt r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL109
    addi r28, r28, -4
    lui r1, %hi(FD4)
    addi r1, r1, %lo(FD4)
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD5)
    addi r1, r1, %lo(FD5)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW20
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD5)
    addi r1, r1, %lo(FD5)
    stw r28, r1, 0
    jal r31, FW25
    jal r0, FL110
FL109:
    addi r28, r28, 4
FL110:
FL108:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : XY
FW64:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 28
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sll r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sll r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sll r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
FL111:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : TUBE-ON
FW65:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, tube_init
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL113
    addi r28, r28, -4
    lui r1, %hi(FD7)
    addi r1, r1, %lo(FD7)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 24
    stw r28, r1, 0
    jal r31, FW48
    addi r1, r0, 10
    debug r1
    jal r31, FW19
    jal r0, FL112
FL113:
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    ldw r3, r28, 0
    jal r31, tube_open
    stw r28, r1, 0
    ldw r1, r28, 0
    slt r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL114
    addi r28, r28, -4
    lui r1, %hi(FD8)
    addi r1, r1, %lo(FD8)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 21
    stw r28, r1, 0
    jal r31, FW48
    addi r1, r0, 10
    debug r1
    jal r31, FW19
    jal r0, FL112
FL114:
    jal r31, FW18
FL112:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : GLASS-KEY
FW66:
    addi r27, r27, -4
    stw r27, r31, 0
FL116:
    addi r28, r28, -4
    lui r1, %hi(FD9)
    addi r1, r1, %lo(FD9)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 4
    stw r28, r1, 0
    ldw r4, r28, 0
    ldw r3, r28, 4
    addi r28, r28, 4
    jal r31, tube_keys
    stw r28, r1, 0
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL117
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r0, FL115
FL117:
    addi r28, r28, -4
    lui r1, %hi(FD9)
    addi r1, r1, %lo(FD9)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 2
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL118
    addi r28, r28, -4
    lui r1, %hi(FD9)
    addi r1, r1, %lo(FD9)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD9)
    addi r1, r1, %lo(FD9)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldbu r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 8
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sll r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    jal r0, FL115
FL118:
    jal r0, FL116
FL115:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : MOVE
FW67:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    jal r31, FW64
    jal r31, FW63
FL119:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : DRAW
FW68:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 2
    stw r28, r1, 0
    jal r31, FW64
    jal r31, FW63
FL120:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : POINT
FW69:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 3
    stw r28, r1, 0
    jal r31, FW64
    jal r31, FW63
FL121:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : INTEN
FW70:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 255
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, 262144
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    jal r31, FW63
FL122:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : COLOR
FW71:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, 4096
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, 327680
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    or r2, r2, r1
    stw r28, r2, 0
    jal r31, FW63
FL123:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : WIPE
FW72:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD5)
    addi r1, r1, %lo(FD5)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL124:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : PRESENT
FW73:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    jal r31, FW63
    addi r28, r28, -4
    lui r1, %hi(FD4)
    addi r1, r1, %lo(FD4)
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD5)
    addi r1, r1, %lo(FD5)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD6)
    addi r1, r1, %lo(FD6)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r5, r28, 0
    ldw r4, r28, 4
    ldw r3, r28, 8
    addi r28, r28, 8
    jal r31, tube_present
    stw r28, r1, 0
    addi r28, r28, 4
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD6)
    addi r1, r1, %lo(FD6)
    stw r28, r1, 0
    jal r31, FW25
    jal r31, FW72
FL125:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SIN64
FW74:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 63
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    jal r31, FW20
    addi r28, r28, -4
    lui r1, %hi(FD10)
    addi r1, r1, %lo(FD10)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
FL126:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : COS64
FW75:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    jal r31, FW74
FL127:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : WRAP
FW76:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, 16
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
FL128:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : >SCREEN
FW77:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD11)
    addi r1, r1, %lo(FD11)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD12)
    addi r1, r1, %lo(FD12)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
FL129:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : ROTATED
FW78:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW4
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW74
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW75
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    sub r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 256
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
    jal r31, FW3
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW75
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW74
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    addi r1, r0, 256
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
FL130:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : AT+
FW79:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW77
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    jal r31, FW2
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -1
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    and r2, r2, r1
    stw r28, r2, 0
FL131:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SHAPE
FW80:
    addi r27, r27, -4
    stw r27, r31, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    addi r27, r27, -4
    stw r27, r1, 0
    addi r28, r28, -4
    addi r1, r0, 60
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW78
    jal r31, FW79
    jal r31, FW67
    addi r28, r28, -4
    addi r1, r0, -30
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 20
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW78
    jal r31, FW79
    jal r31, FW68
    addi r28, r28, -4
    addi r1, r0, -30
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, -20
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW78
    jal r31, FW79
    jal r31, FW68
    addi r28, r28, -4
    addi r1, r0, 60
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    ldw r1, r27, 0
    addi r27, r27, 4
    addi r28, r28, -4
    stw r28, r1, 0
    jal r31, FW78
    jal r31, FW79
    jal r31, FW68
FL132:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : SHIP-ONE
FW81:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW80
FL133:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : STEP-FLY
FW82:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD11)
    addi r1, r1, %lo(FD11)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD13)
    addi r1, r1, %lo(FD13)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    jal r31, FW76
    addi r28, r28, -4
    lui r1, %hi(FD11)
    addi r1, r1, %lo(FD11)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, %hi(FD12)
    addi r1, r1, %lo(FD12)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD14)
    addi r1, r1, %lo(FD14)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    jal r31, FW76
    addi r28, r28, -4
    lui r1, %hi(FD12)
    addi r1, r1, %lo(FD12)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL134:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : THRUST
FW83:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    lui r1, %hi(FD13)
    addi r1, r1, %lo(FD13)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW75
    addi r28, r28, -4
    addi r1, r0, 8
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD13)
    addi r1, r1, %lo(FD13)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, %hi(FD14)
    addi r1, r1, %lo(FD14)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    jal r31, FW74
    addi r28, r28, -4
    addi r1, r0, 8
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    div r2, r2, r1
    stw r28, r2, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    add r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD14)
    addi r1, r1, %lo(FD14)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL135:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : KEYS
FW84:
    addi r27, r27, -4
    stw r27, r31, 0
FL137:
    jal r31, FW66
    jal r31, FW8
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL138
    addi r28, r28, -4
    addi r1, r0, 258
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    bne r1, r2, FL140
    addi r28, r28, 4
    addi r28, r28, -4
    addi r1, r0, 2
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    jal r31, FW25
    jal r0, FL139
FL140:
    addi r28, r28, -4
    addi r1, r0, 259
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    bne r1, r2, FL141
    addi r28, r28, 4
    addi r28, r28, -4
    addi r1, r0, -2
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    jal r31, FW25
    jal r0, FL139
FL141:
    addi r28, r28, -4
    addi r1, r0, 256
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    bne r1, r2, FL142
    addi r28, r28, 4
    jal r31, FW83
    jal r0, FL139
FL142:
    addi r28, r28, -4
    addi r1, r0, 27
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    bne r1, r2, FL143
    addi r28, r28, 4
    jal r31, FW19
    addi r28, r28, -4
    lui r1, %hi(FD16)
    addi r1, r1, %lo(FD16)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    jal r0, FL139
FL143:
    addi r28, r28, 4
FL139:
    jal r0, FL137
FL138:
FL136:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : FRAME
FW85:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW72
    addi r28, r28, -4
    addi r1, r0, 220
    stw r28, r1, 0
    jal r31, FW70
    lui r1, %hi(FD17)
    addi r1, r1, %lo(FD17)
    ldw r1, r1, 0
    jalr r31, r1, 0
    jal r31, FW73
FL144:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : FLY
FW86:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW18
    addi r28, r28, -4
    lui r1, %hi(FD16)
    addi r1, r1, %lo(FD16)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
FL146:
    jal r31, FW84
    lui r1, %hi(FD18)
    addi r1, r1, %lo(FD18)
    ldw r1, r1, 0
    jalr r31, r1, 0
    jal r31, FW85
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r3, r28, 0
    addi r28, r28, 4
    addi r2, r0, 1000
    mul r3, r3, r2
    jal r31, usleep
    addi r28, r28, -4
    lui r1, %hi(FD16)
    addi r1, r1, %lo(FD16)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r1, r1, 0
    stw r28, r1, 0
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL146
    addi r28, r28, -4
    lui r1, %hi(FD19)
    addi r1, r1, %lo(FD19)
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 22
    stw r28, r1, 0
    jal r31, FW48
    jal r31, FW77
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r28, r2, 0
    stw r28, r1, 4
    jal r31, FDOT
    jal r31, FDOT
    addi r1, r0, 10
    debug r1
FL145:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# : MAIN
FW87:
    addi r27, r27, -4
    stw r27, r31, 0
    jal r31, FW65
    ldw r1, r28, 0
    seq r1, r1, r0
    stw r28, r1, 0
    ldw r1, r28, 0
    addi r28, r28, 4
    beq r1, r0, FL148
    jal r0, FL147
FL148:
    jal r31, FW86
FL147:
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

# entry: top-level statements, then MAIN if defined
FMAIN:
    addi r27, r27, -4
    stw r27, r31, 0
    addi r28, r28, -4
    addi r1, r0, 1
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD6)
    addi r1, r1, %lo(FD6)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -2048
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD11)
    addi r1, r1, %lo(FD11)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, 1
    addi r1, r1, -2048
    stw r28, r1, 0
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    addi r28, r28, 4
    mul r2, r2, r1
    stw r28, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FD12)
    addi r1, r1, %lo(FD12)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD13)
    addi r1, r1, %lo(FD13)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    addi r1, r0, 0
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD14)
    addi r1, r1, %lo(FD14)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    addi r1, r0, 16
    stw r28, r1, 0
    addi r28, r28, -4
    lui r1, %hi(FD15)
    addi r1, r1, %lo(FD15)
    stw r28, r1, 0
    ldw r1, r28, 0
    ldw r2, r28, 4
    stw r1, r2, 0
    addi r28, r28, 8
    addi r28, r28, -4
    lui r1, %hi(FW81)
    addi r1, r1, %lo(FW81)
    stw r28, r1, 0
    lui r1, %hi(FD17)
    addi r1, r1, %lo(FD17)
    ldw r2, r28, 0
    addi r28, r28, 4
    stw r1, r2, 0
    addi r28, r28, -4
    lui r1, %hi(FW82)
    addi r1, r1, %lo(FW82)
    stw r28, r1, 0
    lui r1, %hi(FD18)
    addi r1, r1, %lo(FD18)
    ldw r2, r28, 0
    addi r28, r28, 4
    stw r1, r2, 0
    jal r31, FW87
    ldw r31, r27, 0
    addi r27, r27, 4
    jalr r0, r31, 0

.data
FBASE: .word 10
FD0:
.space 4
FD1:
.space 4
FD2:
.space 68
FD3:
.space 4
FD4:
.space 65536
FD5:
.space 4
FD6:
.space 4
FD7:
.byte 78,111,32,116,117,98,101,58,32,97,116,116,97,99,104,32,97,32,115,99,114,101,101,110
FD8:
.byte 116,117,98,101,58,32,118,101,99,32,111,112,101,110,32,102,97,105,108,101,100
FD9:
.space 4
FD10:
.word 0
.word 25
.word 50
.word 74
.word 98
.word 121
.word 142
.word 162
.word 181
.word 198
.word 213
.word 226
.word 237
.word 245
.word 251
.word 255
.word 256
.word 255
.word 251
.word 245
.word 237
.word 226
.word 213
.word 198
.word 181
.word 162
.word 142
.word 121
.word 98
.word 74
.word 50
.word 25
.word 0
.word -25
.word -50
.word -74
.word -98
.word -121
.word -142
.word -162
.word -181
.word -198
.word -213
.word -226
.word -237
.word -245
.word -251
.word -255
.word -256
.word -255
.word -251
.word -245
.word -237
.word -226
.word -213
.word -198
.word -181
.word -162
.word -142
.word -121
.word -98
.word -74
.word -50
.word -25
FD11:
.space 4
FD12:
.space 4
FD13:
.space 4
FD14:
.space 4
FD15:
.space 4
FD16:
.space 4
FD17:
.word 0
FD18:
.word 0
FD19:
.byte 111,107,44,32,116,104,101,32,115,104,105,112,32,104,111,108,100,115,32,97,116,32
.bss
fdstack: .space 16384
fdstack_top:
frstack: .space 16384
frstack_top:
fpad: .space 4
