#include <stdio.h>
#include <stdint.h>

#define MAX_SRC 8192

static char g_src[MAX_SRC];

static int read_file(const char *path, char *buf, uint32_t max_len, uint32_t *out_len) {
    FILE *f;
    uint32_t n;
    int ch;

    f = fopen(path, "rb");
    if (!f) return 0;
    n = 0;
    for (;;) {
        ch = fgetc(f);
        if (ch == EOF) break;
        if (n + 1 >= max_len) {
            fclose(f);
            return 0;
        }
        buf[n] = (char)ch;
        n = n + 1;
    }
    fclose(f);
    buf[n] = 0;
    *out_len = n;
    return 1;
}

static int has_main_symbol(const char *s) {
    uint32_t i = 0;
    while (s[i] != 0) {
        if (s[i] == 'm' && s[i + 1] == 'a' && s[i + 2] == 'i' && s[i + 3] == 'n') {
            return 1;
        }
        i = i + 1;
    }
    return 0;
}

static int emit_min_asm(const char *out_path) {
    FILE *f = fopen(out_path, "wb");
    if (!f) return 0;
    if (fputs("# Generated by Stage 8 cc-min spike\n", f) < 0) { fclose(f); return 0; }
    if (fputs(".text\n", f) < 0) { fclose(f); return 0; }
    if (fputs("main:\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    .global main\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r29, r29, -256\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    stw r29, r31, 252\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    stw r29, r30, 248\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r30, r29, 256\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r1, r0, 0\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    jal r0, .L0\n", f) < 0) { fclose(f); return 0; }
    if (fputs(".L0:\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    ldw r31, r29, 252\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    ldw r30, r29, 248\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r29, r29, 256\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    jalr r0, r31, 0\n", f) < 0) { fclose(f); return 0; }
    if (fclose(f) != 0) return 0;
    return 1;
}

int main(int argc, char **argv) {
    uint32_t src_len;
    if (argc != 3) {
        fprintf(stderr, "usage: %s <input.c> <output.s>\n", argv[0]);
        return 1;
    }
    if (!read_file(argv[1], g_src, MAX_SRC, &src_len)) {
        fprintf(stderr, "error: unable to read %s\n", argv[1]);
        return 1;
    }
    (void)src_len;
    if (!has_main_symbol(g_src)) {
        fprintf(stderr, "error: no main symbol found\n");
        return 1;
    }
    if (!emit_min_asm(argv[2])) {
        fprintf(stderr, "error: unable to write %s\n", argv[2]);
        return 1;
    }
    return 0;
}
