RECORD TYPE=L,LENGTH=20
JOINKEYS F1=CUST,FIELDS=(1,4,A)
JOINKEYS F2=ORD,FIELDS=(1,4,A)
JOIN UNPAIRED
REFORMAT FIELDS=(?,F1:1,4,F2:1,4,F1:6,8,F2:12,6)
SORT FIELDS=COPY
OUTFIL FNAMES=PAIRED,INCLUDE=(1,1,CH,EQ,C'B')
OUTFIL FNAMES=LONE,SAVE
