; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc -mtriple=slow32-unknown-none < %s | FileCheck %s

declare i64 @__udivdi3(i64, i64)

define i32 @extract_udiv_hi() {
; CHECK-LABEL: extract_udiv_hi:
; CHECK:       jal r31, __udivdi3
; CHECK-NEXT:  add r1, r2, r0
entry:
  %q = tail call i64 @__udivdi3(i64 1234, i64 10)
  %hi = lshr i64 %q, 32
  %res = trunc i64 %hi to i32
  ret i32 %res
}

define void @spill_udiv(ptr nocapture %dst) {
; CHECK-LABEL: spill_udiv:
; CHECK:       add [[PTR:r[0-9]+]], r3, r0
; CHECK:       jal r31, __udivdi3
; CHECK:       stw [[PTR]]+4, r2
; CHECK-NEXT:  stw [[PTR]]+0, r1
entry:
  %q = tail call i64 @__udivdi3(i64 987654321, i64 3)
  store i64 %q, ptr %dst, align 4
  ret void
}
