#!/bin/bash
# Build the COBOL runtime for SLOW-32.
#
# cobol/ is in the tree's ordinary universe, so the host toolchain builds
# guest code -- the same arrangement fortran/ and every other app use.
# Which host compiler that is, LLVM or the self-hosted stage08 cc, is
# cctool.sh's business.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
. "$ROOT/cobol/cctool.sh"

# The hook thunks (docs/dbt-hooks.md): each hookable routine's entry is a
# jump to its _impl, carrying __s32hk_<name>_<tag>, the tag the cksum of
# kern.h -- computed the same way tools/dbt/Makefile computes it.
tag=$(cksum < "$HERE/kern.h" | awk '{printf "%08x", $1}')
hk="$HERE/libcob_hk.s"
{
    echo "# generated by libcob/build.sh from kern.h -- the hook thunks"
    printf '\t.text\n'
    for f in cob_get_num cob_put_num_x; do
        printf '\t.globl %s\n\t.globl __s32hk_%s_%s\n%s:\n__s32hk_%s_%s:\n\tjal r0, %s_impl\n' \
            "$f" "$f" "$tag" "$f" "$f" "$tag" "$f"
    done
} > "$hk"
S32_CC_APPEND="$hk" s32_cc_obj "$HERE/libcob.s32o" "$HERE/libcob.c" -I"$HERE"
echo "built: $HERE/libcob.s32o ($s32_cc_backend)"
