#!/bin/bash
# Build the COBOL runtime for SLOW-32.
#
# cobol/ is in the tree's ordinary universe, so the host toolchain builds
# guest code -- the same arrangement fortran/ and every other app use.
# Which host compiler that is, LLVM or the self-hosted stage08 cc, is
# cctool.sh's business.
#
# LIBCOB_OUT=dir puts the objects (and everything made on the way) there
# and leaves this directory alone: tests/selfhost-libcob.sh builds the
# runtime a second time, with the other compiler, beside the one in use.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
. "$ROOT/cobol/cctool.sh"
OUT="${LIBCOB_OUT:-$HERE}"

# What is appended to the compiler's assembly: entries.s, and the hook
# thunks (docs/dbt-hooks.md): each hookable routine's entry is a
# jump to its _impl, carrying __s32hk_<name>_<tag>, the tag the cksum of
# kern.h -- computed the same way tools/dbt/Makefile computes it.
tag=$(cksum < "$HERE/kern.h" | awk '{printf "%08x", $1}')
hk="$OUT/libcob_hk.s"
{
    echo "# generated by libcob/build.sh from kern.h -- the hook thunks"
    printf '\t.text\n'
    for f in cob_get_num cob_put_num_x cob_get_edited cob_put_edited cob_sort_run; do
        printf '\t.globl %s\n\t.globl __s32hk_%s_%s\n%s:\n__s32hk_%s_%s:\n\tjal r0, %s_impl\n' \
            "$f" "$f" "$tag" "$f" "$f" "$tag" "$f"
    done
    # the entries written out by hand (PERFORM's push and exit)
    cat "$HERE/entries.s"
} > "$hk"
S32_CC_APPEND="$hk" s32_cc_obj "$OUT/libcob.s32o" "$HERE/libcob.c" -I"$HERE"
echo "built: $OUT/libcob.s32o ($s32_cc_backend)"
# the EXEC SQL runtime (docs/esql.md), linked only into programs with SQL
s32_cc_obj "$OUT/esql.s32o" "$HERE/esql.c" -I"$HERE" -I"$ROOT/sqlite"
echo "built: $OUT/esql.s32o"
