#!/usr/bin/env python3
"""Generate casemap.h: Unicode simple case mappings for UPPER-CASE and
LOWER-CASE (cobol ISSUES-66).

COBOL 2002 Annex D note 1: implementors should use the case mappings in
UnicodeData.txt; without a locale the result has the argument's length,
so only the one-to-one (simple) mappings, fields 12 and 13, are used.
The source is libutf's copy (Unicode 16.0), so the two agree; the
output is Unicode data under the Unicode License V3 (NOTICE):

    libcob/gen_casemap.py [~/utf/gen/data/UnicodeData.txt] > libcob/casemap.h

Each table is a sorted list of runs {lo, hi, stride, delta}: every code
point lo, lo+stride, ... hi maps to itself plus delta.
"""
import os, sys

path = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/utf/gen/data/UnicodeData.txt")
upper, lower = {}, {}
for line in open(path):
    f = line.rstrip("\n").split(";")
    cp = int(f[0], 16)
    if f[12]: upper[cp] = int(f[12], 16)
    if f[13]: lower[cp] = int(f[13], 16)

# the national path keeps a character's width in code units: a BMP letter's
# other case is in the BMP, a supplementary letter's is supplementary
for m in (upper, lower):
    assert all((cp >= 0x10000) == (v >= 0x10000) for cp, v in m.items()), "a mapping crosses the BMP"

def runs(m):
    out = []
    for cp in sorted(m):
        d = m[cp] - cp
        if out:
            lo, hi, st, dd = out[-1]
            if dd == d and ((lo == hi and cp - hi in (1, 2)) or (lo != hi and cp - hi == st)):
                out[-1] = (lo, cp, cp - lo if lo == hi else st, d)
                continue
        out.append((cp, cp, 1, d))
    return out

def emit(name, m):
    r = runs(m)
    back = {cp: cp + d for lo, hi, st, d in r for cp in range(lo, hi + 1, st)}
    assert back == m, name + ": the runs do not reproduce the mappings"
    print(f"static const cob_caserun {name}[{len(r)}] = {{")
    for i in range(0, len(r), 4):
        print("    " + " ".join(f"{{ 0x{lo:05X}, 0x{hi:05X}, {st}, {d} }}," for lo, hi, st, d in r[i:i + 4]))
    print("};")

print("/* Generated by gen_casemap.py from libutf's UnicodeData.txt (Unicode 16.0; Unicode License V3, see NOTICE); do not edit. */")
print("typedef struct { unsigned lo, hi; unsigned char stride; int delta; } cob_caserun;")
emit("cob_case_upper", upper)
emit("cob_case_lower", lower)
