/* kern.h -- libcob's hookable kernels (docs/dbt-hooks.md).
 *
 * The code in this file is compiled twice: into libcob for SLOW-32, and
 * into slow32-dbt for the host, where it is the native implementation of
 * a hooked routine.  Both builds tag the hooks with the cksum of this
 * file, so any edit here -- to a kernel, a constant, a comment -- turns
 * the hooks off in every DBT built before it, until that DBT is rebuilt.
 * That is the point: the DBT never runs a kernel whose contract it has
 * not seen.
 *
 * Rules for everything here:
 *   - no globals but const tables, no calls outside this file (memset,
 *     memcpy excepted), no pointers read out of guest memory (a caller
 *     resolves those and passes what they point at);
 *   - the constants and the descriptor layout the kernels depend on are
 *     restated here, not taken from cobrt.h, so this file's checksum is
 *     the whole contract; libcob.c checks them against cobrt.h at compile
 *     time;
 *   - types are sized alike on both sides: int and unsigned are 32 bits,
 *     long long 64.
 *
 * The hookable routines (thunks generated by build.sh, `jal r0, <name>_impl`):
 *   long long cob_get_num(const void *p, const cob_desc *d)
 *       r3 = p, r4 = d; the result in r1:r2
 *   int cob_put_num_x(void *p, const cob_desc *d, long long v, int vscale, int opts)
 *       r3 = p, r4 = d, r5:r6 = v, r7 = vscale, r8 = opts; the result in r1
 *   int cob_put_edited(void *p, const cob_desc *d, long long v, int vscale, int opts, int locale)
 *       as cob_put_num_x, locale in r9 (K_LOC_*)
 *   long long cob_get_edited(const void *p, const cob_desc *d, int locale)
 *       r3 = p, r4 = d, r5 = locale; the result in r1:r2
 * A hook takes a descriptor when cob_k_get_ok / cob_k_put_ok / cob_k_ed_ok
 * say so, and declines everything else to the _impl, which is the
 * reference. */
#ifndef COB_KERN_H
#define COB_KERN_H

#include <string.h>

#define KFN static inline __attribute__((unused))

/* cobrt.h's values, restated (libcob.c checks they agree) */
enum { K_NUM_ED = 4 };                                      /* cat */
enum { K_U_DISPLAY = 0, K_U_BINARY = 1, K_U_PACKED = 2, K_U_NATIONAL = 3, K_U_BIT = 4 };
enum { K_F_SIGNED = 1, K_F_SEPLEAD = 2, K_F_SEPTRAIL = 4, K_F_BLANKZ = 16, K_F_NOTRUNC = 32, K_F_LEAD = 64 };
enum { K_F2_BIGEND = 1, K_F2_NOSIGN = 2, K_F2_TWOSC = 4, K_F2_SIZEDIG = 8 };   /* flags2 */

/* cob_desc as the guest lays it out, the PICTURE pointer a 32-bit guest
 * address */
typedef struct {
    unsigned char cat, usage, digits;
    signed char   scale;
    unsigned char flags, flags2, pad[2];
    unsigned int  size;
    unsigned int  pic;
} cob_kdesc;

static const long long pow10tab[19] = {
    1LL, 10LL, 100LL, 1000LL, 10000LL, 100000LL, 1000000LL, 10000000LL,
    100000000LL, 1000000000LL, 10000000000LL, 100000000000LL, 1000000000000LL,
    10000000000000LL, 100000000000000LL, 1000000000000000LL,
    10000000000000000LL, 100000000000000000LL, 1000000000000000000LL
};

/* ---- digits without 64-bit division ---------------------------------- */
/* SLOW-32 divides 32 bits in hardware and 64 bits a bit at a time (some
 * 600 instructions), and a numeric item is at most 18 digits: so the
 * digit loops work nine digits at a time in a 32-bit word, two digits a
 * step through a pairs table, and a division by a power of ten is by a
 * constant in every case, which the compiler turns into a multiply. */
static const char digit_pairs[201] =
    "00010203040506070809" "10111213141516171819" "20212223242526272829"
    "30313233343536373839" "40414243444546474849" "50515253545556575859"
    "60616263646566676869" "70717273747576777879" "80818283848586878889"
    "90919293949596979899";

/* the low n digits of mag as characters, the least significant at out[n-1] */
KFN void mag_to_digits(unsigned long long mag, char *out, int n)
{
    while (n > 0) {
        unsigned lo; int take;
        if (mag >> 32) { unsigned long long q = mag / 1000000000ULL; lo = (unsigned)(mag - q * 1000000000ULL); mag = q; take = 9; }
        else { lo = (unsigned)mag; mag = 0; take = n; }
        if (take > n) take = n;
        n -= take;
        char *o = out + n + take;
        while (take >= 2) { unsigned q = lo / 100u, r = lo - q * 100u; *--o = digit_pairs[r * 2 + 1]; *--o = digit_pairs[r * 2]; lo = q; take -= 2; }
        if (take) *--o = (char)('0' + lo % 10u);
    }
}

/* a / 10^m, the remainder through *rem */
KFN unsigned long long udiv_pow10(unsigned long long a, int m, unsigned long long *rem)
{
    unsigned long long q;
    if (m <= 0) { *rem = 0; return a; }
    if (!(a >> 32) && m <= 9) { unsigned x = (unsigned)a, d = (unsigned)pow10tab[m], qq = x / d; *rem = x - qq * d; return qq; }
    switch (m) {
    case 1: q = a / 10ULL; break;
    case 2: q = a / 100ULL; break;
    case 3: q = a / 1000ULL; break;
    case 4: q = a / 10000ULL; break;
    case 5: q = a / 100000ULL; break;
    case 6: q = a / 1000000ULL; break;
    case 7: q = a / 10000000ULL; break;
    case 8: q = a / 100000000ULL; break;
    case 9: q = a / 1000000000ULL; break;
    case 10: q = a / 10000000000ULL; break;
    case 11: q = a / 100000000000ULL; break;
    case 12: q = a / 1000000000000ULL; break;
    case 13: q = a / 10000000000000ULL; break;
    case 14: q = a / 100000000000000ULL; break;
    case 15: q = a / 1000000000000000ULL; break;
    case 16: q = a / 10000000000000000ULL; break;
    case 17: q = a / 100000000000000000ULL; break;
    case 18: q = a / 1000000000000000000ULL; break;
    default: *rem = a; return 0;
    }
    *rem = a - q * (unsigned long long)pow10tab[m];
    return q;
}

/* -u as a signed value.  Every negation of a value that may be INT64_MIN
 * goes through unsigned arithmetic here: -v is undefined there, and the
 * two compilers that build this file (the slow32 clang, stage08's cc)
 * answered it differently (kern-differential, 2026-09-29).  The unsigned
 * to signed conversion is two's complement on every compiler we use. */
KFN long long k_neg(unsigned long long u) { return (long long)(0 - u); }

/* v / 10^m with C's truncation toward zero, the remainder v's sign */
KFN long long div_pow10(long long v, int m, long long *rem)
{
    unsigned long long r, q = udiv_pow10(v < 0 ? 0 - (unsigned long long)v : (unsigned long long)v, m, &r);
    if (rem) *rem = v < 0 ? k_neg(r) : (long long)r;
    return v < 0 ? k_neg(q) : (long long)q;
}

/* ---- cob_get_num: DISPLAY, PACKED-DECIMAL and BINARY of up to 18 digits */

/* the descriptors the kernel reads: not 31 digits, not national or bit,
 * not numeric-edited */
KFN int cob_k_get_ok(const cob_kdesc *d)
{
    if (d->digits > 18 || (d->usage == K_U_BINARY && d->size > 8)) return 0;
    if (d->usage == K_U_NATIONAL || d->usage == K_U_BIT) return 0;
    if (d->cat == K_NUM_ED) return 0;
    return d->usage == K_U_DISPLAY || d->usage == K_U_BINARY || d->usage == K_U_PACKED;
}

/* Value of the item scaled by 10^scale (i.e. the integer the digits spell). */
KFN long long cob_k_get_num(const unsigned char *p, const cob_kdesc *d)
{
    long long v = 0;
    int neg = 0;
    switch (d->usage) {
    case K_U_BINARY: {
        unsigned long long u = 0;
        if (d->flags2 & K_F2_BIGEND) for (unsigned i = 0; i < d->size; i++) u = (u << 8) | p[i];
        else for (int i = (int)d->size - 1; i >= 0; i--) u = (u << 8) | p[i];
        if ((d->flags & K_F_SIGNED) && d->size < 8 && ((u >> (d->size * 8 - 1)) & 1))
            u |= ~0ULL << (d->size * 8);
        return (long long)u;
    }
    case K_U_PACKED: {
        int bytes = (int)d->size;
        /* the high nibble of the first byte is a pad when the digits do not
         * fill the nibbles (an even count with a sign, an odd one without):
         * not a digit, whatever it holds -- content nobody promised (a group
         * MOVE put '0' = 0x30 there) read as the picture reads it, as the
         * compiler's in-line decoders and GnuCOBOL do (gen-native seed 51) */
        unsigned b0 = 2 * bytes - ((d->flags2 & K_F2_NOSIGN) ? 0 : 1) - d->digits > 0 ? (p[0] & 15u) : p[0];
        if (d->flags2 & K_F2_NOSIGN) {                  /* COMP-6: every nibble a digit */
            unsigned long long u = (b0 >> 4) * 10 + (b0 & 15);
            for (int i = 1; i < bytes; i++) u = u * 100 + (p[i] >> 4) * 10 + (p[i] & 15);
            return (long long)u;
        }
        /* eight digits at a time in a 32-bit word (the flush into v kept
         * out of the byte loop: inside it the compiler if-converts it into
         * a 64-bit multiply on every byte) */
        int i = 0, first = 1;
        while (i < bytes - 1) {
            int len = bytes - 1 - i < 4 ? bytes - 1 - i : 4, stop = i + len;
            unsigned w = 0;
            for (; i < stop; i++) { unsigned b = i ? p[i] : b0; w = w * 100 + (b >> 4) * 10 + (b & 15); }
            v = first ? (long long)w : v * pow10tab[2 * len] + w; first = 0;
        }
        v = v * 10 + (p[bytes - 1] >> 4);
        if ((p[bytes - 1] & 15) == 0xD) v = -v;
        return v;
    }
    default: {
        /* DISPLAY: digits, with the sign either overpunched on the last
         * digit ('p'..'y' = negative 0..9), or separate leading/trailing */
        int n = (int)d->size, i = 0;
        if (d->flags & K_F_SEPLEAD) { neg = (p[0] == '-'); i = 1; }
        int end = n;
        if (d->flags & K_F_SEPTRAIL) { neg = (p[n - 1] == '-'); end = n - 1; }
        /* nine digits at a time in a 32-bit word; the flush into v stays
         * outside the character loop (inside, the compiler if-converts it
         * into a 64-bit multiply on every character) */
        int first = 1;
        while (i < end) {
            int len = end - i < 9 ? end - i : 9, stop = i + len;
            unsigned w = 0;
            for (; i < stop; i++) {
                unsigned c = (unsigned)p[i] - '0';
                if (c > 9) {
                    unsigned char ch = p[i];
                    if (ch >= 'p' && ch <= 'y') { c = ch - 'p'; neg = 1; }     /* overpunch: last digit, or first with SIGN LEADING */
                    else if (ch == ' ') c = 0;              /* a space counts as zero */
                    /* Anything else: the low nibble.  This is no parity
                     * with GnuCOBOL (it substitutes a zero digit: '001B'
                     * reads 10 there, 12 here), and it is not the EBCDIC
                     * overpunch a file converted from a mainframe carries
                     * (zone C = +0..+9 over {ABCDEFGHI, zone D = -0..-9
                     * over }JKLMNOPQR): the nibble gives the right digit
                     * for A..I only, and 10..13 for the rest, which then
                     * corrupt the accumulated number, and it drops the
                     * sign of J..R.  p..y for -0..-9 is the ASCII
                     * overpunch this toolchain writes, so nothing it
                     * produces reaches this line; reading EBCDIC-derived
                     * data would need the zone, not the nibble. */
                    else c = ch & 15;
                }
                w = w * 10 + c;
            }
            v = first ? (long long)w : v * pow10tab[len] + w; first = 0;
        }
        return neg ? -v : v;
    }
    }
}

/* ---- cob_put_num_x: the same descriptors, as a receiver --------------- */

KFN int cob_k_put_ok(const cob_kdesc *d) { return cob_k_get_ok(d); }

/* v (scaled by vscale) aligned to the item's scale by truncation (or
 * ROUNDED) and truncated to its high-order digits (unless the usage says
 * the binary field's capacity is the limit): its sign and magnitude, or a
 * size error.  cob_k_put_num stores that; libcob's numeric-edited path
 * edits it.  eff is the digit
 * positions that hold a character: d->digits less the PICTURE's P
 * symbols, which the caller counts (the PICTURE is a pointer).
 * opts: 1 = ROUNDED (nearest, ties away from zero -- the 85 rule),
 * 2 = report a size error instead of truncating.  Returns 1 on a size
 * error (nothing stored), else 0. */
KFN int cob_k_put_scale(const cob_kdesc *d, int eff, long long v, int vscale, int opts, int *negp, unsigned long long *magp)
{
    if (vscale > d->scale) {
        int m = vscale - d->scale;
        long long k = pow10tab[m > 18 ? 18 : m], r;
        long long q = div_pow10(v, m, &r);
        unsigned long long ar = r < 0 ? 0 - (unsigned long long)r : (unsigned long long)r;
        if ((opts & 1) && ar >= ((unsigned long long)k + 1) / 2) q += (v < 0) ? -1 : 1;   /* |r| * 2 >= k, without the overflow */
        v = q;
    } else if (vscale < d->scale) {
        /* scaling up can pass 64 bits (12345 into 9V9(17)): the size error
         * is decided on the integer digits first, then the digits that
         * cannot survive the receiver's width are dropped before the shift */
        int k = d->scale - vscale;
        if (!(d->flags & K_F_NOTRUNC) && d->digits <= 18) {
            unsigned long long a = v < 0 ? 0 - (unsigned long long)v : (unsigned long long)v;
            int lim = eff - d->scale + vscale;           /* integer positions, in v's scale */
            if (opts & 2) {
                if (lim < 0 ? a != 0 : (lim <= 18 && a >= (unsigned long long)pow10tab[lim])) return 1;
            }
            int keep = eff - k;
            if (keep <= 0) v = 0; else if (keep <= 18 && a >= (unsigned long long)pow10tab[keep]) div_pow10(v, keep, &v);
        }
        if (v) v = (long long)((unsigned long long)v * (unsigned long long)pow10tab[k > 18 ? 18 : k]);   /* wraps, as the guest always has */
    }

    int neg = v < 0;
    unsigned long long mag = neg ? 0 - (unsigned long long)v : (unsigned long long)v;
    if (d->flags & K_F_NOTRUNC) {
        if ((opts & 2) && (d->flags2 & K_F2_SIZEDIG) && d->digits <= 18 && mag >= (unsigned long long)pow10tab[d->digits]) return 1;
        if ((opts & 2) && d->size < 8) {
            unsigned long long lim = 1ULL << (d->size * 8 - ((d->flags & K_F_SIGNED) ? 1 : 0));
            if (mag >= lim) return 1;
        }
    } else if (d->digits <= 18) {
        if (mag >= (unsigned long long)pow10tab[eff]) {
            if (opts & 2) return 1;
            udiv_pow10(mag, eff, &mag);
        }
    }
    if (!(d->flags & K_F_SIGNED) && !(d->flags2 & K_F2_TWOSC)) neg = 0;   /* unsigned takes the magnitude (a COMP-X MOVE: two's complement) */
    *negp = neg; *magp = mag;
    return 0;
}

KFN int cob_k_put_num(unsigned char *p, const cob_kdesc *d, int eff, long long v, int vscale, int opts)
{
    int neg; unsigned long long mag;
    if (cob_k_put_scale(d, eff, v, vscale, opts, &neg, &mag)) return 1;
    switch (d->usage) {
    case K_U_BINARY: {
        long long s = neg ? k_neg(mag) : (long long)mag;
        if (d->flags2 & K_F2_BIGEND) for (unsigned i = 0; i < d->size; i++) p[d->size - 1 - i] = (unsigned char)(s >> (8 * i));
        else for (unsigned i = 0; i < d->size; i++) p[i] = (unsigned char)(s >> (8 * i));
        break;
    }
    case K_U_PACKED: {
        int digits = d->digits, bytes = (int)d->size;
        char dg[20];
        mag_to_digits(mag, dg, digits);
        if (d->flags2 & K_F2_NOSIGN) {                  /* COMP-6: the digits right-aligned, no sign */
            int k = digits - 1;
            for (int j = bytes - 1; j >= 0; j--, k -= 2) {
                unsigned lo = k >= 0 ? (unsigned)(dg[k] - '0') : 0u, hi = k > 0 ? (unsigned)(dg[k - 1] - '0') : 0u;
                p[j] = (unsigned char)((hi << 4) | lo);
            }
            break;
        }
        /* the last digit shares its byte with the sign; the rest pair off
         * leftwards, a zero nibble at the front when the count is even */
        int k = digits - 1, j = bytes - 1;
        p[j] = (unsigned char)(((dg[k] - '0') << 4) | ((d->flags & K_F_SIGNED) ? (neg ? 0xD : 0xC) : 0xF));
        for (k--; k >= 0; k -= 2) {
            unsigned hi = k > 0 ? (unsigned)(dg[k - 1] - '0') : 0u;
            p[--j] = (unsigned char)((hi << 4) | (unsigned)(dg[k] - '0'));
        }
        while (j > 0) p[--j] = 0;
        break;
    }
    default: {
        int n = (int)d->size, i = n - 1, start = 0;
        if ((d->flags & K_F_BLANKZ) && mag == 0) { for (int j = 0; j < n; j++) p[j] = ' '; break; }   /* BLANK WHEN ZERO on a plain numeric item */
        if (d->flags & K_F_SEPLEAD) { p[0] = neg ? '-' : '+'; start = 1; }
        if (d->flags & K_F_SEPTRAIL) { p[n - 1] = neg ? '-' : '+'; i = n - 2; }
        mag_to_digits(mag, (char *)p + start, i - start + 1);
        if (neg && !(d->flags & (K_F_SEPLEAD | K_F_SEPTRAIL))) {
            int k = (d->flags & K_F_LEAD) ? 0 : n - 1;
            p[k] = (unsigned char)(p[k] - '0' + 'p');
        }
        break;
    }
    }
    return 0;
}

/* ---- the software edit descriptor, applied and reversed --------------
 *
 * (Was cobedit.h, shared with s32-cobc once; now libcob's alone.)  The
 * descriptor is the flattened PICTURE symbol string that
 * picture.c produces: one character per position, CR/DB as 'C'/'D', with
 * V/S/P kept so the point is known.  cobc370 handed the same information
 * to the S/370 ED instruction as a mask; here it is walked in C.
 *
 * Rules are the 1985 PICTURE clause: zero suppression (Z, *), floating
 * insertion (+, -, $ -- n symbols give n-1 digit positions and the symbol
 * lands immediately left of the first significant character), simple
 * insertion (, B 0 /) replaced by the fill character while suppression is
 * in force, fixed signs (+ - CR DB), the decimal point ending suppression,
 * BLANK WHEN ZERO, and the all-suppressed zero.
 */

KFN char cob_edit_floating(const char *pat)
{
    int cp = 0, cm = 0, cd = 0;
    for (const char *p = pat; *p; p++) { if (*p == '+') cp++; else if (*p == '-') cm++; else if (*p == '$') cd++; }
    return cp > 1 ? '+' : cm > 1 ? '-' : cd > 1 ? '$' : 0;
}

/* Edit the digit string digs (exactly the picture's digit positions,
 * integer part then fraction) into out.  Returns the number of bytes
 * written (the item's width). */
KFN int cob_edit_apply(const char *pat, const char *digs, int neg, int blank_zero, char *out)
{
    char fl = cob_edit_floating(pat);
    int fl_seen = 0, flpos = -1;
    char fill = strchr(pat, '*') ? '*' : ' ';
    int zero = 1, has9 = 0, npos = 0;
    for (const char *p = pat; *p; p++) {
        if (*p == '9') has9 = 1;
        if (*p == '9' || *p == 'Z' || *p == '*' || (fl && *p == fl)) npos++;
    }
    if (fl) npos--;
    for (int i = 0; i < npos; i++) if (digs[i] != '0') { zero = 0; break; }
    /* the value edited is the value after truncation (X3.23-1985 VI-34,
     * rule 7), and zero is "positive or zero" in the sign table: -32745520
     * into $9+ is 0, so $0+, not $0- (tests/gen found it) */
    if (zero) neg = 0;

    /* a zero value in a picture whose every digit position is check-
     * protected (*) and none is 9: all asterisks but the decimal point */
    if (zero && fill == '*' && !has9) {
        int o = 0;
        for (const char *p = pat; *p; p++) {
            if (*p == '.') out[o++] = '.';
            else if (*p == 'C' || *p == 'D') { out[o++] = '*'; out[o++] = '*'; }   /* CR/DB: one symbol, two bytes (a p++ here once walked past the string's end) */
            else out[o++] = '*';
        }
        return o;
    }
    /* instr: a zero-suppression or floating string has begun.  A simple
     * insertion character (, B 0 /) is part of that string when embedded
     * in it or immediately right of it, and takes the fill while
     * suppression lasts; outside one it is always itself (X3.23-1985
     * VI-34, VI-35, editing rules 7 and 8).  '0' was always '0', so
     * $0$$.99 holding .42 gave " 0$.42" for "  $.42"; and an insertion
     * character before any such string took the fill (tests/gen found
     * them; tests/free/editins). */
    int sig = 0, di = 0, o = 0, first_sig = -1, instr = 0;
    for (const char *p = pat; *p; p++) {
        char c = *p;
        if (fl && c == fl) {
            instr = 1;
            if (!fl_seen) { fl_seen = 1; flpos = o; out[o++] = fill; continue; }
            char d = digs[di++];
            if (d != '0' || sig) { if (!sig) { sig = 1; first_sig = o; } out[o++] = d; }
            else out[o++] = fill;
            continue;
        }
        switch (c) {
        case '9': { char d = digs[di++]; if (!sig) { sig = 1; first_sig = o; } out[o++] = d; break; }
        case 'Z': case '*': {
            instr = 1;
            char d = digs[di++];
            if (d != '0' || sig) { if (!sig) { sig = 1; first_sig = o; } out[o++] = d; }
            else out[o++] = fill;
            break;
        }
        case '.': if (!sig) { sig = 1; first_sig = o; } out[o++] = '.'; break;
        case ',': out[o++] = !sig && instr ? fill : ','; break;
        case 'B': out[o++] = !sig && instr ? fill : ' '; break;
        case '0': out[o++] = !sig && instr ? fill : '0'; break;
        case '/': out[o++] = !sig && instr ? fill : '/'; break;
        case '+': out[o++] = neg ? '-' : '+'; break;
        case '-': out[o++] = neg ? '-' : ' '; break;
        case '$': out[o++] = '$'; break;
        case 'C': out[o++] = neg ? 'C' : ' '; out[o++] = neg ? 'R' : ' '; break;
        case 'D': out[o++] = neg ? 'D' : ' '; out[o++] = neg ? 'B' : ' '; break;
        default: break;                          /* V S P: no character */
        }
    }
    int width = o;

    if (blank_zero && zero) { memset(out, ' ', (size_t)width); return width; }

    if (fl) {
        if (first_sig < 0 || (zero && !has9)) {
            /* every digit position floats and the value is zero: spaces
             * (the decimal point and the currency symbol too) */
            memset(out, ' ', (size_t)width);
        } else {
            int pos = first_sig - 1;
            if (pos < flpos) pos = flpos;
            out[pos] = fl == '$' ? '$' : fl == '+' ? (neg ? '-' : '+') : (neg ? '-' : ' ');
        }
        return width;
    }
    if (zero && !has9) {
        /* all Z or all *: spaces throughout, or asterisks around the point */
        for (int i = 0; i < width; i++)
            if (fill == ' ' || out[i] != '.') out[i] = fill == ' ' ? ' ' : (out[i] == '.' ? '.' : '*');
        if (fill == '*') {
            /* keep fixed sign / currency / CR DB positions as edited */
            int k = 0;
            for (const char *p = pat; *p; p++) {
                if (*p == '+' || *p == '-' || *p == '$') { out[k] = (*p == '$') ? '$' : (*p == '+' ? '+' : ' '); k++; }
                else if (*p == 'C' || *p == 'D') { out[k] = out[k + 1] = ' '; k += 2; }
                else if (*p != 'V' && *p != 'S' && *p != 'P') k++;
            }
        }
    }
    return width;
}

/* Reverse: the digits and sign of an edited item.  digs receives exactly
 * the picture's digit positions. Returns the digit count. */
KFN int cob_deedit(const char *pat, const unsigned char *bytes, char *digs, int *neg)
{
    char fl = cob_edit_floating(pat);
    int fl_seen = 0, bi = 0, di = 0, minus = 0;
    for (const char *p = pat; *p; p++) {
        char c = *p;
        if (fl && c == fl) {
            if (!fl_seen) { fl_seen = 1; if (bytes[bi] == '-') minus = 1; bi++; continue; }
            unsigned char b = bytes[bi++];
            if (b == '-') minus = 1;
            digs[di++] = (b >= '0' && b <= '9') ? (char)b : '0';
            continue;
        }
        switch (c) {
        case '9': case 'Z': case '*': {
            unsigned char b = bytes[bi++];
            digs[di++] = (b >= '0' && b <= '9') ? (char)b : '0';
            break;
        }
        case '+': case '-': if (bytes[bi] == '-') minus = 1; bi++; break;
        case 'C': case 'D': if (bytes[bi] == 'C' || bytes[bi] == 'D') minus = 1; bi += 2; break;
        case '.': case ',': case 'B': case '0': case '/': case '$':
            if (bytes[bi] == '-') minus = 1;
            bi++; break;
        default: break;
        }
    }
    *neg = minus;
    return di;
}


/* ---- numeric-edited store and fetch ------------------------------------
 * The program's DECIMAL-POINT IS COMMA and CURRENCY SIGN choices come in
 * as locale: bit 0 the comma, bits 8-15 the currency character. */
#define K_LOC_COMMA(l)    ((l) & 1)
#define K_LOC_CURRENCY(l) (((l) >> 8) & 255)

KFN int cob_k_ed_ok(const cob_kdesc *d)
{
    return d->cat == K_NUM_ED && d->digits <= 18 && d->usage == K_U_DISPLAY;
}

/* v (scaled by vscale) into a numeric-edited item: the scaling of
 * cob_k_put_scale, then the edit, then the locale's characters.  pic is
 * the item's PICTURE, eff its digit positions (less the P symbols). */
KFN int cob_k_put_edited(unsigned char *p, const cob_kdesc *d, const char *pic, int eff,
                         long long v, int vscale, int opts, int locale)
{
    int neg; unsigned long long mag;
    if (cob_k_put_scale(d, eff, v, vscale, opts, &neg, &mag)) return 1;
    char digs[40];
    memset(digs, '0', sizeof digs);          /* a PICTURE with more positions than eff reads zeros, not the stack */
    mag_to_digits(mag, digs, eff > 38 ? 38 : eff);
    int w = cob_edit_apply(pic, digs, neg, d->flags & K_F_BLANKZ, (char *)p);
    int cur = K_LOC_CURRENCY(locale);
    if (K_LOC_COMMA(locale)) for (int i = 0; i < w; i++) { if (p[i] == '.') p[i] = ','; else if (p[i] == ',') p[i] = '.'; }
    if (cur != '$') for (int i = 0; i < w; i++) if (p[i] == '$') p[i] = (unsigned char)cur;
    return 0;
}

/* The value of a numeric-edited item (de-editing, a 1985 feature IBM ANS
 * COBOL never had): its bytes read with the locale undone, then the
 * digits and sign the PICTURE places. */
KFN long long cob_k_get_edited(const unsigned char *p, const cob_kdesc *d, const char *pic, int locale)
{
    long long v = 0;
    int neg = 0;
    char digs[40];
    unsigned char sw[256];
    int cur = K_LOC_CURRENCY(locale);
    if ((K_LOC_COMMA(locale) || cur != '$') && d->size <= sizeof sw) {     /* the bytes carry ',' for the point, c for '$': read them the other way round */
        for (unsigned i = 0; i < d->size; i++) {
            unsigned char c = p[i];
            if (K_LOC_COMMA(locale)) c = c == '.' ? ',' : c == ',' ? '.' : c;
            if (cur != '$' && c == (unsigned char)cur) c = '$';
            sw[i] = c;
        }
        p = sw;
    }
    int n = cob_deedit(pic, p, digs, &neg);
    for (int i = 0; i < n; i++) v = v * 10 + (digs[i] - '0');
    return neg ? k_neg((unsigned long long)v) : v;
}

#endif
