#!/usr/bin/env python3
"""Generate term_width.h: the display width of each code point, for the
term service's Unicode-aware screen and COBOL Report Writer columns.

wcwidth's convention, from libutf's copy of the Unicode 16.0 data so the
two agree:
  2  East Asian Width W or F (EastAsianWidth.txt)
  0  general category Mn, Me, Cf (but U+00AD SOFT HYPHEN, 1), and the Hangul
     medial and final jamo U+1160..U+11FF, which combine with a leading one
  1  everything else, East Asian Ambiguous included
Control characters are the caller's business.

    tools/emulator/gen_term_width.py [datadir] > common/term_width.h

The table is sorted runs {lo, hi, width} of the code points whose width is
not 1; term_width() searches it.
"""
import os, re, sys

data = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/utf/gen/data")
w = {}
for line in open(os.path.join(data, "EastAsianWidth.txt")):
    line = line.split("#")[0].strip()
    if not line: continue
    rng, cls = [x.strip() for x in line.split(";")]
    if cls not in ("W", "F"): continue
    lo, _, hi = rng.partition("..")
    lo = int(lo, 16); hi = int(hi or lo, 16) if hi else lo
    for cp in range(lo, hi + 1): w[cp] = 2
prev = None
for line in open(os.path.join(data, "UnicodeData.txt")):
    f = line.split(";")
    cp, name, cat = int(f[0], 16), f[1], f[2]
    ranges = [(cp, cp)]
    if name.endswith(", Last>") and prev is not None: ranges = [(prev + 1, cp)]
    prev = cp if name.endswith(", First>") else None
    if cat in ("Mn", "Me", "Cf") and cp != 0x00AD:
        for lo, hi in ranges:
            for c in range(lo, hi + 1): w[c] = 0
for cp in range(0x1160, 0x1200): w[cp] = 0

runs = []
for cp in sorted(w):
    if runs and runs[-1][1] == cp - 1 and runs[-1][2] == w[cp]: runs[-1][1] = cp
    else: runs.append([cp, cp, w[cp]])
back = {c: r[2] for r in runs for c in range(r[0], r[1] + 1)}
assert back == w, "the runs do not reproduce the widths"

print("/* Generated by tools/emulator/gen_term_width.py from libutf's Unicode 16.0")
print(" * data (EastAsianWidth.txt, UnicodeData.txt); do not edit. */")
print("#ifndef S32_TERM_WIDTH_H")
print("#define S32_TERM_WIDTH_H")
print("typedef struct { unsigned lo, hi; unsigned char width; } s32_width_run;")
print(f"static const s32_width_run s32_width_runs[{len(runs)}] = {{")
for i in range(0, len(runs), 4):
    print("    " + " ".join(f"{{ 0x{lo:05X}, 0x{hi:05X}, {wd} }}," for lo, hi, wd in runs[i:i + 4]))
print("};")
print("""/* a code point's display width: 0, 1 or 2 (not for control characters) */
static inline int s32_term_width(unsigned cp)
{
    int lo = 0, hi = (int)(sizeof s32_width_runs / sizeof *s32_width_runs) - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (cp < s32_width_runs[mid].lo) hi = mid - 1;
        else if (cp > s32_width_runs[mid].hi) lo = mid + 1;
        else return s32_width_runs[mid].width;
    }
    return 1;
}
#endif""")
