# Generated by Stage 4 Bootstrap C Compiler
.text
print_str:
    .global print_str
    addi r29, r29, -256
    stw r29, r31, 252
    stw r29, r30, 248
    addi r30, r29, 256
    stw r30, r3, -12
.L1:
    addi r1, r30, -12
    ldw r1, r1, 0
    ldb r1, r1, 0
    bne r1, r0, .L3
    jal r0, .L2
.L3:
    addi r1, r30, -12
    ldw r1, r1, 0
    ldb r1, r1, 0
    addi r3, r1, 0
    call putchar
    addi r1, r30, -12
    addi r29, r29, -4
    stw r29, r1, 0
    addi r1, r30, -12
    ldw r1, r1, 0
    addi r29, r29, -4
    stw r29, r1, 0
    addi r1, r0, 1
    ldw r2, r29, 0
    addi r29, r29, 4
    add r1, r2, r1
    ldw r2, r29, 0
    addi r29, r29, 4
    stw r2, r1, 0
    jal r0, .L1
.L2:
.L0:
    ldw r31, r29, 252
    ldw r30, r29, 248
    addi r29, r29, 256
    jalr r0, r31, 0

main:
    .global main
    addi r29, r29, -256
    stw r29, r31, 252
    stw r29, r30, 248
    addi r30, r29, 256
    la r1, .Lstr_0
    addi r3, r1, 0
    call print_str
    addi r1, r0, 0
    jal r0, .L4
.L4:
    ldw r31, r29, 252
    ldw r30, r29, 248
    addi r29, r29, 256
    jalr r0, r31, 0

.data
    .align 4
.Lstr_0:
    .byte 72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 10, 0
.text
