#!/usr/bin/env python3
"""Generate common/s32utf_tables.h from libutf (~/utf, MIT, Unicode 16.0).

The display-width, Grapheme_Cluster_Break and Extended_Pictographic DFAs
are copied from libutf's generated tables, as they are: the same tables
tinymux uses, so SLOW-32's terminal, the COBOL runtime and the compiler
measure text the way a TinyMUX server does.  s32utf.h holds the code that
runs them.

    python3 common/gen_s32utf.py [UTF_DIR] > common/s32utf_tables.h
"""
import os, re, sys

UTF = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/utf")
src = open(os.path.join(UTF, "tables", "unicode_tables_ext.c")).read()
hdr = open(os.path.join(UTF, "include", "utf", "utf_tables.h")).read()

NAMES = ["tr_widths", "tr_gcb", "cl_extpict"]
PARTS = ["itt", "sot", "sbt"]

out = ["/* s32utf_tables.h -- GENERATED by common/gen_s32utf.py from libutf",
       " * (github.com/brazilofmux/utf, MIT license, Unicode 16.0):",
       " * tables/unicode_tables_ext.c and include/utf/utf_tables.h.",
       " * Do not edit; regenerate.  The code that runs these is s32utf.h. */",
       "#ifndef S32UTF_TABLES_H", "#define S32UTF_TABLES_H", ""]
for n in NAMES:
    for d in ("START_STATE", "ACCEPTING_STATES_START"):
        m = re.search(r"#define %s_%s \((\d+)\)" % (n.upper(), d), hdr)
        if not m:
            sys.exit("no %s_%s in utf_tables.h" % (n.upper(), d))
        out.append("#define S32U_%s_%s %s" % (n.upper(), d, m.group(1)))
    for p in PARTS:
        m = re.search(r"const (unsigned (?:char|short)) %s_%s\[(\d+)\] =\s*\{(.*?)\};" % (n, p), src, re.S)
        if not m:
            sys.exit("no %s_%s in unicode_tables_ext.c" % (n, p))
        body = " ".join(m.group(3).split())
        out.append("static const %s s32u_%s_%s[%s] = { %s };" % (m.group(1), n, p, m.group(2), body))
    out.append("")
out.append("#endif")
print("\n".join(out))
