\ Test string utility words

\ --- PICK ---
: T-PICK1  1 2 3  0 PICK . 1 PICK . 2 PICK . CR 2DROP DROP ;
T-PICK1

\ --- CMOVE (forward copy) ---
CREATE BUF1 16 ALLOT
: T-CMOVE
  S" HELLO" DROP BUF1 5 CMOVE
  BUF1 5 TYPE CR ;
T-CMOVE

\ --- CMOVE> (backward copy) ---
CREATE BUF2 16 ALLOT
: T-CMOVEB
  S" WORLD" DROP BUF2 5 CMOVE>
  BUF2 5 TYPE CR ;
T-CMOVEB

\ --- /STRING ---
: T-SLSTR
  S" ABCDEF" 2 /STRING TYPE CR ;
T-SLSTR

\ --- COMPARE ---
: T-CMP1  S" ABC" S" ABC" COMPARE . CR ;
: T-CMP2  S" ABC" S" ABD" COMPARE . CR ;
: T-CMP3  S" ABD" S" ABC" COMPARE . CR ;
: T-CMP4  S" AB" S" ABC" COMPARE . CR ;
: T-CMP5  S" ABC" S" AB" COMPARE . CR ;
: T-CMP6  S" " S" " COMPARE . CR ;
T-CMP1 T-CMP2 T-CMP3 T-CMP4 T-CMP5 T-CMP6

\ --- SEARCH ---
: T-SRCH1  S" HELLO WORLD" S" WORLD" SEARCH . TYPE CR ;
: T-SRCH2  S" HELLO WORLD" S" XYZ" SEARCH . TYPE CR ;
: T-SRCH3  S" HELLO" S" " SEARCH . TYPE CR ;
: T-SRCH4  S" ABCABC" S" ABC" SEARCH . TYPE CR ;
T-SRCH1 T-SRCH2 T-SRCH3 T-SRCH4

\ --- PLACE + COUNT roundtrip ---
CREATE BUF3 32 ALLOT
: T-PLACE
  S" TEST" BUF3 PLACE
  BUF3 COUNT TYPE CR ;
T-PLACE

\ --- -TRAILING ---
: T-TRAIL1  S" hi   " -TRAILING TYPE ." |" CR ;
: T-TRAIL2  S" hello" -TRAILING TYPE ." |" CR ;
: T-TRAIL3  S" " -TRAILING TYPE ." |" CR ;
T-TRAIL1 T-TRAIL2 T-TRAIL3

BYE
