#include <stdio.h>

int ccmin_get_ret_imm(void);

static int emit_min_asm(const char *out_path, int ret_imm) {
    FILE *f = fopen(out_path, "wb");
    if (!f) return 0;
    if (fputs("# Generated by Stage 8 cc-min spike\n", f) < 0) { fclose(f); return 0; }
    if (fputs(".text\n", f) < 0) { fclose(f); return 0; }
    if (fputs("main:\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    .global main\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r29, r29, -256\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    stw r29, r31, 252\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    stw r29, r30, 248\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r30, r29, 256\n", f) < 0) { fclose(f); return 0; }
    if (fprintf(f, "    addi r1, r0, %d\n", ret_imm) < 0) { fclose(f); return 0; }
    if (fputs("    jal r0, .L0\n", f) < 0) { fclose(f); return 0; }
    if (fputs(".L0:\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    ldw r31, r29, 252\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    ldw r30, r29, 248\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    addi r29, r29, 256\n", f) < 0) { fclose(f); return 0; }
    if (fputs("    jalr r0, r31, 0\n", f) < 0) { fclose(f); return 0; }
    if (fclose(f) != 0) return 0;
    return 1;
}

int pass3_emit_from_ir(const char *out_path) {
    return emit_min_asm(out_path, ccmin_get_ret_imm());
}
